// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: query.sql

package querytest

import (
	"context"
)

const test = `-- name: Test :one
SELECT abs(-17.4)
`

func (q *Queries) Test(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, test)
	var abs int64
	err := row.Scan(&abs)
	return abs, err
}
