// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: postgresql.query.sql

package db

import (
	"context"
)

const createTempTable = `-- name: CreateTempTable :exec
CREATE TEMPORARY TABLE bar (LIKE foo)
`

func (q *Queries) CreateTempTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createTempTable)
	return err
}

const selectOne = `-- name: SelectOne :one
SELECT 1
`

func (q *Queries) SelectOne(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, selectOne)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
